language: php

env:
  - DB=mysql
  - DB=sqlite

before_script:
  - mkdir opPostTwitterPlugin
  - mv * opPostTwitterPlugin || true
  - git clone --depth=1 git://github.com/openpne/OpenPNE3.git openpne3
  - cd openpne3
  - git clone --depth=1 git://github.com/K-Phoen/sfTaskExtraPlugin.git plugins/sfTaskExtraPlugin
  - mv ../opTestApiPlugin plugins/

  - cp config/ProjectConfiguration.class.php{.sample,}
  - if [ "$DB" = "mysql" ]; then ./symfony openpne:fast-install --dbms=mysql --dbuser=root --dbpassword= --dbname=openpne; fi
  - if [ "$DB" = "sqlite" ]; then ./symfony openpne:fast-install --dbms=sqlite --dbname=log/op3.sqlite; sudo chgrp -R www-data log; chmod -R g+rw log; fi

script:
  - php ./symfony test:plugin opPostTwitterPlugin
